"""add contract score detail to task executions

Revision ID: 4491ac318ffc
Revises: b6f7846940e8
Create Date: 2026-08-14 16:16:51.017343

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '4491ac318ffc'
down_revision: Union[str, Sequence[str], None] = 'b6f7846940e8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # server_default backfills existing rows; NOT NULL ADD COLUMN fails outright without one
    op.add_column('task_executions', sa.Column('missing_expected_actions', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('task_executions', sa.Column('forbidden_actions_seen', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))
    op.add_column('task_executions', sa.Column('final_state_mismatches', postgresql.JSONB(astext_type=sa.Text()), nullable=False, server_default=sa.text("'[]'::jsonb")))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('task_executions', 'final_state_mismatches')
    op.drop_column('task_executions', 'forbidden_actions_seen')
    op.drop_column('task_executions', 'missing_expected_actions')
    # ### end Alembic commands ###
