"""add trace event type and payload indexes

Forward-looking, not a fix for an active bottleneck: comparison.py currently fetches
each execution's full ordered trace into Python and diffs there, so there is no SQL
query today that filters trace_events by event_type or reaches into payload. These
support the query shapes that divergence detection conceptually cares about (a
type-filtered scan, or a lookup into payload's service/operation/arguments) if that
logic ever moves into SQL. The existing ix_trace_events_execution_id is replaced
rather than kept alongside the new composite index: (execution_id, event_type) serves
plain execution_id-only lookups via its leftmost column just as well, so keeping both
would only add index-maintenance cost with no read benefit.

Revision ID: 82cfbe100ed2
Revises: 9a1faddf3548
Create Date: 2026-08-15 14:56:47.068287

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '82cfbe100ed2'
down_revision: Union[str, Sequence[str], None] = '9a1faddf3548'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_trace_events_execution_id'), table_name='trace_events')
    op.create_index('ix_trace_events_execution_id_event_type', 'trace_events', ['execution_id', 'event_type'], unique=False)
    op.create_index('ix_trace_events_payload_gin', 'trace_events', ['payload'], unique=False, postgresql_using='gin')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trace_events_payload_gin', table_name='trace_events', postgresql_using='gin')
    op.drop_index('ix_trace_events_execution_id_event_type', table_name='trace_events')
    op.create_index(op.f('ix_trace_events_execution_id'), 'trace_events', ['execution_id'], unique=False)
    # ### end Alembic commands ###
