"""create core platform tables

Revision ID: b6f7846940e8
Revises: 
Create Date: 2026-07-13 18:55:06.623162

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'b6f7846940e8'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('agent_versions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('git_sha', sa.String(), nullable=False),
    sa.Column('model', sa.String(), nullable=False),
    sa.Column('system_prompt', sa.String(), nullable=False),
    sa.Column('tool_schema_hash', sa.String(), nullable=False),
    sa.Column('config', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('evaluation_runs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('agent_version_id', sa.Uuid(), nullable=False),
    sa.Column('suite_id', sa.String(), nullable=False),
    sa.Column('suite_version', sa.String(), nullable=False),
    sa.Column('suite_manifest_hash', sa.String(), nullable=False),
    sa.Column('seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('queued', 'running', 'completed', 'failed', name='runstatus'), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['agent_version_id'], ['agent_versions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_evaluation_runs_agent_version_id', 'evaluation_runs', ['agent_version_id'], unique=False)
    op.create_table('task_executions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('run_id', sa.Uuid(), nullable=False),
    sa.Column('task_id', sa.String(), nullable=False),
    sa.Column('task_seed', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('pending', 'running', 'passed', 'failed', 'errored', name='executionstatus'), nullable=False),
    sa.Column('passed', sa.Boolean(), nullable=True),
    sa.Column('final_output', sa.String(), nullable=True),
    sa.Column('latency_ms', sa.Integer(), nullable=True),
    sa.Column('input_tokens', sa.Integer(), nullable=True),
    sa.Column('output_tokens', sa.Integer(), nullable=True),
    sa.Column('estimated_cost_usd', sa.Float(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['run_id'], ['evaluation_runs.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_task_executions_run_id', 'task_executions', ['run_id'], unique=False)
    op.create_index('ix_task_executions_run_id_task_id', 'task_executions', ['run_id', 'task_id'], unique=False)
    op.create_table('trace_events',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('sequence_no', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Enum('model_request', 'model_response', 'tool_call', 'tool_result', 'retry', 'error', 'final_answer', name='eventtype'), nullable=False),
    sa.Column('payload', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('parent_event_id', sa.Uuid(), nullable=True),
    sa.Column('duration_ms', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('execution_id', 'sequence_no', name='uq_trace_events_execution_sequence')
    )
    op.create_index('ix_trace_events_execution_id', 'trace_events', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_trace_events_execution_id', table_name='trace_events')
    op.drop_table('trace_events')
    op.drop_index('ix_task_executions_run_id_task_id', table_name='task_executions')
    op.drop_index('ix_task_executions_run_id', table_name='task_executions')
    op.drop_table('task_executions')
    op.drop_index('ix_evaluation_runs_agent_version_id', table_name='evaluation_runs')
    op.drop_table('evaluation_runs')
    op.drop_table('agent_versions')
    # ### end Alembic commands ###
