"""add judge verdicts table

Revision ID: bd25f8b625ce
Revises: 4491ac318ffc
Create Date: 2026-08-14 16:40:44.066890

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bd25f8b625ce'
down_revision: Union[str, Sequence[str], None] = '4491ac318ffc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('judge_verdicts',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_id', sa.Uuid(), nullable=False),
    sa.Column('judge_name', sa.String(), nullable=False),
    sa.Column('rubric_version', sa.String(), nullable=False),
    sa.Column('label', sa.Enum('pass', 'fail', 'uncertain', name='judgelabel'), nullable=False),
    sa.Column('confidence', sa.Float(), nullable=False),
    sa.Column('rationale', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['execution_id'], ['task_executions.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_judge_verdicts_execution_id', 'judge_verdicts', ['execution_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_judge_verdicts_execution_id', table_name='judge_verdicts')
    op.drop_table('judge_verdicts')
    # ### end Alembic commands ###
